"""
Standarddata for AirBNB-planleggeren.
Denne filen brukes av generate.py for aa lage data.js.
"""

categories = [
    "Bad",
    "Soverom",
    "Gang",
    "Stue",
    "Kjøkken",
    "Bod",
    "Alle rom",
]

days = [
    "4 dager før gjester ankommer",
    "3 dager før gjester ankommer",
    "2 dager før gjester ankommer",
    "1 dag før gjester ankommer",
    "Ankomstdag",
]

priorities = ["Kritisk", "Normal", "Valgfri"]

tasks = [
    {
        "id": "task-001",
        "title": "Fjern alle ikke-sommerklær",
        "category": "Bod",
        "day": "4 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 1,
    },
    {
        "id": "task-002",
        "title": "Hent frem alle sommerklær",
        "category": "Bod",
        "day": "4 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 2,
    },
    {
        "id": "task-003",
        "title": "Vask sommerklær",
        "category": "Bod",
        "day": "4 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 3,
    },
    {
        "id": "task-004",
        "title": "Sjekk status på håndklær og sengetøy",
        "category": "Soverom",
        "day": "4 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 4,
    },
    {
        "id": "task-005",
        "title": "Lag full handleliste",
        "category": "Alle rom",
        "day": "4 dager før gjester ankommer",
        "priority": "Kritisk",
        "completed": False,
        "notes": "Shopping",
        "order": 5,
    },
    {
        "id": "task-006",
        "title": "Vask kjøkkenutstyr",
        "category": "Kjøkken",
        "day": "3 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 1,
    },
    {
        "id": "task-007",
        "title": "Rydd",
        "category": "Kjøkken",
        "day": "3 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 2,
    },
    {
        "id": "task-008",
        "title": "Rydd gang",
        "category": "Gang",
        "day": "3 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 3,
    },
    {
        "id": "task-009",
        "title": "Rydd",
        "category": "Soverom",
        "day": "2 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 1,
    },
    {
        "id": "task-010",
        "title": "Rydd",
        "category": "Bad",
        "day": "2 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 2,
    },
    {
        "id": "task-011",
        "title": "Rydd stue",
        "category": "Stue",
        "day": "2 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 3,
    },
    {
        "id": "task-012",
        "title": "Vask kluter og håndklær",
        "category": "Kjøkken",
        "day": "2 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 4,
    },
    {
        "id": "task-013",
        "title": "Tom kjøleskap og fryser",
        "category": "Kjøkken",
        "day": "2 dager før gjester ankommer",
        "priority": "Kritisk",
        "completed": False,
        "notes": "",
        "order": 5,
    },
    {
        "id": "task-014",
        "title": "Fjern alkohol",
        "category": "Bod",
        "day": "2 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 6,
    },
    {
        "id": "task-015",
        "title": "Fjern sko, jakker og klær",
        "category": "Bod",
        "day": "2 dager før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 7,
    },
    {
        "id": "task-016",
        "title": "Fjern verdisaker (laptop, kabler)",
        "category": "Bod",
        "day": "2 dager før gjester ankommer",
        "priority": "Kritisk",
        "completed": False,
        "notes": "",
        "order": 8,
    },
    {
        "id": "task-017",
        "title": "Siste sjanse for full vask (klær, sengetøy, håndklær osv.)",
        "category": "Soverom",
        "day": "1 dag før gjester ankommer",
        "priority": "Kritisk",
        "completed": False,
        "notes": "",
        "order": 1,
    },
    {
        "id": "task-018",
        "title": "Handle alt på handlelisten",
        "category": "Alle rom",
        "day": "1 dag før gjester ankommer",
        "priority": "Kritisk",
        "completed": False,
        "notes": "Shopping",
        "order": 2,
    },
    {
        "id": "task-019",
        "title": "Vask dusjforheng",
        "category": "Bad",
        "day": "1 dag før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 3,
    },
    {
        "id": "task-020",
        "title": "Steam",
        "category": "Bad",
        "day": "1 dag før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 4,
    },
    {
        "id": "task-021",
        "title": "Fyll opp toalettsaker",
        "category": "Bad",
        "day": "1 dag før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 5,
    },
    {
        "id": "task-022",
        "title": "Støvsug sofa og puter",
        "category": "Stue",
        "day": "1 dag før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 6,
    },
    {
        "id": "task-023",
        "title": "Fjern PC",
        "category": "Kjøkken",
        "day": "1 dag før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 7,
    },
    {
        "id": "task-024",
        "title": "Mute alle Google-høyttalere",
        "category": "Stue",
        "day": "1 dag før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "",
        "order": 8,
    },
    {
        "id": "task-025",
        "title": "Støvsug",
        "category": "Alle rom",
        "day": "1 dag før gjester ankommer",
        "priority": "Kritisk",
        "completed": False,
        "notes": "Hele leiligheten",
        "order": 9,
    },
    {
        "id": "task-026",
        "title": "Støvtørk",
        "category": "Alle rom",
        "day": "1 dag før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "Hele leiligheten",
        "order": 10,
    },
    {
        "id": "task-027",
        "title": "Vask overflater",
        "category": "Alle rom",
        "day": "1 dag før gjester ankommer",
        "priority": "Normal",
        "completed": False,
        "notes": "Hele leiligheten",
        "order": 11,
    },
]

