// AUTO-GENERATED by generate.py — do not edit by hand.
// Edit data.py instead, then re-run: python3 generate.py
const DEFAULT_DATA = {
  "categories": [
    "Bad",
    "Soverom",
    "Gang",
    "Stue",
    "Kj\u00f8kken",
    "Bod",
    "Alle rom"
  ],
  "days": [
    "4 dager f\u00f8r gjester ankommer",
    "3 dager f\u00f8r gjester ankommer",
    "2 dager f\u00f8r gjester ankommer",
    "1 dag f\u00f8r gjester ankommer",
    "Ankomstdag"
  ],
  "priorities": [
    "Kritisk",
    "Normal",
    "Valgfri"
  ],
  "tasks": [
    {
      "id": "task-001",
      "title": "Fjern alle ikke-sommerkl\u00e6r",
      "category": "Bod",
      "day": "4 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 1
    },
    {
      "id": "task-002",
      "title": "Hent frem alle sommerkl\u00e6r",
      "category": "Bod",
      "day": "4 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 2
    },
    {
      "id": "task-003",
      "title": "Vask sommerkl\u00e6r",
      "category": "Bod",
      "day": "4 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 3
    },
    {
      "id": "task-004",
      "title": "Sjekk status p\u00e5 h\u00e5ndkl\u00e6r og senget\u00f8y",
      "category": "Soverom",
      "day": "4 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 4
    },
    {
      "id": "task-005",
      "title": "Lag full handleliste",
      "category": "Alle rom",
      "day": "4 dager f\u00f8r gjester ankommer",
      "priority": "Kritisk",
      "completed": false,
      "notes": "Shopping",
      "order": 5
    },
    {
      "id": "task-006",
      "title": "Vask Kj\u00f8kkenutstyr",
      "category": "Kj\u00f8kken",
      "day": "3 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 1
    },
    {
      "id": "task-007",
      "title": "Rydd",
      "category": "Kj\u00f8kken",
      "day": "3 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 2
    },
    {
      "id": "task-008",
      "title": "Rydd gang",
      "category": "Gang",
      "day": "3 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 3
    },
    {
      "id": "task-009",
      "title": "Rydd",
      "category": "Soverom",
      "day": "2 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 1
    },
    {
      "id": "task-010",
      "title": "Rydd",
      "category": "Bad",
      "day": "2 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 2
    },
    {
      "id": "task-011",
      "title": "Rydd stue",
      "category": "Stue",
      "day": "2 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 3
    },
    {
      "id": "task-012",
      "title": "Vask kluter og h\u00e5ndkl\u00e6r",
      "category": "Kj\u00f8kken",
      "day": "2 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 4
    },
    {
      "id": "task-013",
      "title": "Tom kj\u00f8leskap og fryser",
      "category": "Kj\u00f8kken",
      "day": "2 dager f\u00f8r gjester ankommer",
      "priority": "Kritisk",
      "completed": false,
      "notes": "",
      "order": 5
    },
    {
      "id": "task-014",
      "title": "Fjern alkohol",
      "category": "Bod",
      "day": "2 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 6
    },
    {
      "id": "task-015",
      "title": "Fjern sko, jakker og kl\u00e6r",
      "category": "Bod",
      "day": "2 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 7
    },
    {
      "id": "task-016",
      "title": "Fjern verdisaker (laptop, kabler)",
      "category": "Bod",
      "day": "2 dager f\u00f8r gjester ankommer",
      "priority": "Kritisk",
      "completed": false,
      "notes": "",
      "order": 8
    },
    {
      "id": "task-017",
      "title": "Siste sjanse for full vask (kl\u00e6r, senget\u00f8y, h\u00e5ndkl\u00e6r osv.)",
      "category": "Soverom",
      "day": "1 dag f\u00f8r gjester ankommer",
      "priority": "Kritisk",
      "completed": false,
      "notes": "",
      "order": 1
    },
    {
      "id": "task-018",
      "title": "Handle alt p\u00e5 handlelisten",
      "category": "Alle rom",
      "day": "1 dag f\u00f8r gjester ankommer",
      "priority": "Kritisk",
      "completed": false,
      "notes": "Shopping",
      "order": 2
    },
    {
      "id": "task-019",
      "title": "Vask dusjforheng",
      "category": "Bad",
      "day": "1 dag f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 3
    },
    {
      "id": "task-020",
      "title": "Steam",
      "category": "Bad",
      "day": "1 dag f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 4
    },
    {
      "id": "task-021",
      "title": "Fyll opp toalettsaker",
      "category": "Bad",
      "day": "1 dag f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 5
    },
    {
      "id": "task-022",
      "title": "St\u00f8vsug sofa og puter",
      "category": "Stue",
      "day": "1 dag f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 6
    },
    {
      "id": "task-023",
      "title": "Fjern PC",
      "category": "Kj\u00f8kken",
      "day": "1 dag f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 7
    },
    {
      "id": "task-024",
      "title": "Mute alle Google-h\u00f8yttalere",
      "category": "Stue",
      "day": "1 dag f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "order": 8
    },
    {
      "id": "task-025",
      "title": "St\u00f8vsug",
      "category": "Alle rom",
      "day": "1 dag f\u00f8r gjester ankommer",
      "priority": "Kritisk",
      "completed": false,
      "notes": "Hele leiligheten",
      "order": 9
    },
    {
      "id": "task-026",
      "title": "St\u00f8vt\u00f8rk",
      "category": "Alle rom",
      "day": "1 dag f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "Hele leiligheten",
      "order": 10
    },
    {
      "id": "task-027",
      "title": "Vask overflater",
      "category": "Alle rom",
      "day": "1 dag f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "Hele leiligheten",
      "order": 11
    },
    {
      "id": "drikk-kaffe",
      "title": "Drikk kaffe",
      "category": "Kj\u00f8kken",
      "day": "4 dager f\u00f8r gjester ankommer",
      "priority": "Normal",
      "completed": false,
      "notes": "",
      "assignee": "Meg",
      "order": 6
    }
  ]
};
