"""
Run this after editing data.py:

    python3 generate.py

It reads categories / days / priorities / tasks from data.py and writes
them into data.js, which is the file index.html actually loads (browsers
can't read Python directly). No third-party packages required.
"""

import json
import pathlib

import data

output = {
    "categories": data.categories,
    "days": data.days,
    "priorities": data.priorities,
    "tasks": data.tasks,
}

here = pathlib.Path(__file__).parent
js_path = here / "data.js"

js_content = (
    "// AUTO-GENERATED by generate.py — do not edit by hand.\n"
    "// Edit data.py instead, then re-run: python3 generate.py\n"
    "const DEFAULT_DATA = "
    + json.dumps(output, indent=2)
    + ";\n"
)

js_path.write_text(js_content, encoding="utf-8")
print(f"Wrote {js_path} ({len(data.tasks)} tasks, "
      f"{len(data.categories)} categories, {len(data.days)} days).")
