"""
Lokal server for AirBNB-planleggeren.
Kjør: python server.py
"""

from __future__ import annotations

import importlib.util
import json
import pathlib
import re
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

ROOT = pathlib.Path(__file__).parent
DATA_FILE = ROOT / "data.py"
DATA_JS_FILE = ROOT / "data.js"


def load_data_module():
    spec = importlib.util.spec_from_file_location("planner_data", DATA_FILE)
    if spec is None or spec.loader is None:
        raise RuntimeError("Klarte ikke lese data.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def slugify(text: str) -> str:
    lowered = text.strip().lower()
    lowered = lowered.replace("æ", "ae").replace("ø", "o").replace("å", "a")
    lowered = re.sub(r"[^a-z0-9]+", "-", lowered)
    return lowered.strip("-") or "oppgave"


def next_task_id(tasks: list[dict], title: str) -> str:
    base = slugify(title)
    taken = {item.get("id", "") for item in tasks}
    if base not in taken:
        return base
    i = 2
    while True:
        candidate = f"{base}-{i}"
        if candidate not in taken:
            return candidate
        i += 1


def render_data_py(categories, days, priorities, tasks) -> str:
    return (
        '"""\n'
        "Standarddata for AirBNB-planleggeren.\n"
        "Denne filen brukes av generate.py for aa lage data.js.\n"
        '"""\n\n'
        f"categories = {repr(categories)}\n\n"
        f"days = {repr(days)}\n\n"
        f"priorities = {repr(priorities)}\n\n"
        f"tasks = {repr(tasks)}\n"
    )


def write_data_js(categories, days, priorities, tasks):
    payload = {
        "categories": categories,
        "days": days,
        "priorities": priorities,
        "tasks": tasks,
    }
    content = (
        "// AUTO-GENERATED by server.py - do not edit by hand.\n"
        "// Edit data.py or use the UI permanent task save.\n"
        "const DEFAULT_DATA = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n"
    )
    DATA_JS_FILE.write_text(content, encoding="utf-8")


class PlannerHandler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def _send_json(self, status: int, payload: dict):
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self):
        if self.path != "/api/permanent-tasks":
            self._send_json(404, {"error": "Fant ikke endpoint"})
            return

        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length)

        try:
            payload = json.loads(raw.decode("utf-8"))
        except json.JSONDecodeError:
            self._send_json(400, {"error": "Ugyldig JSON"})
            return

        title = str(payload.get("title", "")).strip()
        category = str(payload.get("category", "Alle rom")).strip() or "Alle rom"
        day = str(payload.get("day", "")).strip()
        priority = str(payload.get("priority", "Normal")).strip() or "Normal"
        notes = str(payload.get("notes", "")).strip()
        assignee = str(payload.get("assignee", "")).strip()

        if not title:
            self._send_json(400, {"error": "Tittel er påkrevd"})
            return

        module = load_data_module()
        categories = list(module.categories)
        days = list(module.days)
        priorities = list(module.priorities)
        tasks = list(module.tasks)

        if category not in categories:
            self._send_json(400, {"error": "Ugyldig rom/kategori"})
            return

        if day and day not in days:
            self._send_json(400, {"error": "Ugyldig dag"})
            return

        if priority not in priorities:
            self._send_json(400, {"error": "Ugyldig prioritet"})
            return

        if assignee not in {"", "Meg", "Vasker"}:
            self._send_json(400, {"error": "Ugyldig ansvarlig"})
            return

        same_day_tasks = [t for t in tasks if t.get("day") == day]
        order = max([int(t.get("order", 0)) for t in same_day_tasks] + [0]) + 1

        new_task = {
            "id": next_task_id(tasks, title),
            "title": title,
            "category": category,
            "day": day,
            "priority": priority,
            "completed": False,
            "notes": notes,
            "assignee": assignee,
            "order": order,
        }

        tasks.append(new_task)

        DATA_FILE.write_text(
            render_data_py(categories, days, priorities, tasks),
            encoding="utf-8",
        )
        write_data_js(categories, days, priorities, tasks)

        self._send_json(201, {"ok": True, "task": new_task})


def main():
    port = 8000
    server = ThreadingHTTPServer(("127.0.0.1", port), PlannerHandler)
    print(f"Starter lokal server på http://127.0.0.1:{port}")
    print("Trykk Ctrl+C for aa stoppe serveren.")
    server.serve_forever()


if __name__ == "__main__":
    main()

